apiVersion: apps/v1
kind: Deployment
metadata:
  name: moooves-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moooves-frontend
  template:
    metadata:
      labels:
        app: moooves-frontend
    spec:
      containers:
        - name: api
          image: IMAGE_NAME
          ports:
            - containerPort: 5555
---
apiVersion: v1
kind: Service
metadata:
  name: moooves-frontend
spec:
  ports:
    - port: 80
      targetPort: 5555
      protocol: TCP
  selector:
    app: moooves-frontend
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: moooves-frontend
spec:
  rules:
    - host: moves.bajescu.com
      http:
        paths:
          - backend:
              serviceName: moooves-frontend
              servicePort: 80
