moves:
  - title: Right handed turn variation
    tags: [Remy, Right Handed, Footwork]
    videos: [{url: "https://www.youtube.com/watch?v=_gjHdBd5wp4", start: 00:53, end: 00:57}]
  - title: Glorias-like variation for Sugar Push turn
    tags: [Skye, Currently Learning, Footwork]
    videos: [{url: "https://www.youtube.com/watch?v=BzmgTqOkmAI", start: 02:42, end: 02:48}]
  - title: Back-to-back Jig Kicks
    tags: [Felipe, Currently Learning]
    videos: [{url: "https://www.youtube.com/watch?v=2gGxtDgt07s", start: 02:18, end: 02:33}]
  - title: Leader's underm-arm into quick follow turn
    tags: [Felipe, Currently Learning]
    videos: [{url: "https://www.youtube.com/watch?v=x_w6LkCmr0w", start: 01:05, end: 01:11}]
  - title: Going forward sugar-push variation
    tags: [Felipe, Currently Learning, Sugar Push Variation, Footwork]
    videos: [{url: "https://www.youtube.com/watch?v=x_w6LkCmr0w", start: 01:25, end: 01:33}]
  - title: Swingout into closed with no-prep extra turn
    tags: [Remy, Swingout]
    videos: [{url: "https://www.youtube.com/watch?v=_gjHdBd5wp4", start: 01:27, end: 01:31}]
  - title: Swingout into open with prepped extra turn
    tags: [Felipe, Swingout]
    videos: [{url: "https://www.youtube.com/watch?v=x_w6LkCmr0w", start: 03:59, end: 04:04}]
  - title: Double handed turn into hand-to-hand
    tags: [Skye, Charleston]
    videos: [{url: "https://www.youtube.com/watch?v=yPHlFOyIlQA", start: 01:44, end: 01:49}]
  - title: Pass-by with hopping
    tags: [Skye, Pass-By Variations, Footwork]
    videos: [{url: "https://www.youtube.com/watch?v=yPHlFOyIlQA", start: 00:48, end: 00:52}]
  - title: Circle with final swinging kick
    tags: [Skye, Footwork]


    
    videos:
      - {url: "https://www.youtube.com/watch?v=18IkHPqY1nU", start: 01:49, end: 01:53}
      - {url: "https://www.youtube.com/watch?v=yPHlFOyIlQA", start: 01:13, end: 01:16}
  - title: Side to side circle
    tags: [Felipe]
    videos: [{url: "https://www.youtube.com/watch?v=x_w6LkCmr0w", start: 00:48, end: 00:58}]
  - title: Leader under-hand into follow turn
    tags: [Nils, Power Move, Currently Learning]
    videos: [{url: "https://www.youtube.com/watch?v=VI04hZILOuY", start: 01:05, end: 01:09}]
  - title: Right hand barrel roll
    tags: [Remy, Right Hand, Barrel Roll]
    videos: [{url: "https://www.youtube.com/watch?v=dmPnOYaBSFE", start: 05:55, end: 06:02}]
  - title: Wiggly tuck-turn variation into pass-by variation
    tags: [Remy, Footwork]
    videos: [{url: "https://www.youtube.com/watch?v=dmPnOYaBSFE", start: 04:31, end: 04:39}]
  - title: Eight count drop with send-out
    tags: [Remy, Footwork]
    videos: [{url: "https://www.youtube.com/watch?v=dmPnOYaBSFE", start: 04:56, end: 05:01}]
  - title: Step-hop circle
    tags: [Smiltys, Footwork]
    videos: [{url: "https://www.youtube.com/watch?v=9ll4TqUvYQY", start: 03:10, end: 03:15}]




