apiVersion: apps/v1
kind: Deployment
metadata:
  name: moooves-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moooves-backend
  template:
    metadata:
      labels:
        app: moooves-backend
    spec:
      containers:
        - name: api
          image: IMAGE_NAME
          ports:
            - containerPort: 5555
---
apiVersion: v1
kind: Service
metadata:
  name: moooves-backend
spec:
  ports:
    - port: 80
      targetPort: 5555
      protocol: TCP
  selector:
    app: moooves-backend
